; @file Trabajo Práctico N° 2 ~ Electronica Digitales II
; @brief
; @detalis Implementacion para PIC16F887 en MPLAB X com MPASM
; @author Rafael Fariñas
; @version 1.0
; @fecha : 3/4/2026
    
; DIRECTIVAS DE INCLUSION 
LIST P = 16F887
#include "p16f887.inc"
;**** Configuración General ****
__CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF

CBLOCK  0x20
	; VARIABLES PARA RETARDO 1s
        DELAY1_Init
        DELAY2_Init
        DELAY3_Init
        DELAY1
        DELAY2
        DELAY3
	; VARIABLES PARA RETARDO 300ms
	DELAY4_Init
	DELAY5_Init
	DELAY6_Init
	DELAY4
	DELAY5
	DELAY6
	; VARIABLES PARA RETARDO 200ms
	DELAY7_Init
	DELAY8_Init
	DELAY9_Init
	DELAY7
	DELAY8
	DELAY9
	; VARIABLES PARA RETARDO 100ms
	DELAY10_Init
	DELAY11_Init
	DELAY12_Init
	DELAY10
	DELAY11
	DELAY12
	; CONTADORES PARA LEDS PARA REPETIR PATRONES 3 VECES C/U
	CONT_RL
	CONT_BRL
	CONT_CRAW
ENDC
